version: '3.8'

services:
  broker_mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


  master:
    image: 10.1.2.112:5000/tpf-master
    depends_on:
      - broker_mqtt
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure


  slave-nj:
    image: 10.1.2.112:5000/tpf-slave-nj
    depends_on:
      - master
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure

  slave-py:
    image: 10.1.2.112:5000/tpf-slave-py
    depends_on:
      - master
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure

  web:
    image: 10.1.2.112:5000/tpf-web-ui
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure



