# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_slave.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12master_slave.proto\x12\x0cmaster_slave\"9\n\tSlaveInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\'\n\x14RegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x06Result\x12\x10\n\x08slave_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\"\n\x0f\x41\x63knowledgement\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa5\x01\n\x12MasterSlaveService\x12L\n\rRegisterSlave\x12\x17.master_slave.SlaveInfo\x1a\".master_slave.RegistrationResponse\x12\x41\n\nSendResult\x12\x14.master_slave.Result\x1a\x1d.master_slave.Acknowledgementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_slave_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLAVEINFO._serialized_start=36
  _SLAVEINFO._serialized_end=93
  _REGISTRATIONRESPONSE._serialized_start=95
  _REGISTRATIONRESPONSE._serialized_end=134
  _RESULT._serialized_start=136
  _RESULT._serialized_end=176
  _ACKNOWLEDGEMENT._serialized_start=178
  _ACKNOWLEDGEMENT._serialized_end=212
  _MASTERSLAVESERVICE._serialized_start=215
  _MASTERSLAVESERVICE._serialized_end=380
# @@protoc_insertion_point(module_scope)
